apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats
  labels:
    app: stats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats
  template:
    metadata:
      labels:
        app: stats
    spec:
      containers:
      - name: stats
        image: traggeret/timer_client:latest
