apiVersion: apps/v1
kind: Deployment
metadata:
  name: timer-app-depl
  labels:
    app: timer-app-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timer-app-depl
  template:
    metadata:
      labels:
        app: timer-app-depl
    spec:
      containers:
      - name: timer-app-depl
        image: traggeret/timer_server:latest
        ports:
        - containerPort: 7777
          protocol: TCP
          name: http
