FROM ubuntu:latest

RUN apt-get update -y
RUN apt-get install -y python3-pip python3-dev build-essential python3-flask
COPY ./src/server /myapp_server
WORKDIR /myapp_server 
EXPOSE 7777
ENTRYPOINT ["python3"]
CMD ["timer.py"]
